version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres
    container_name: pet-finder-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  
volumes:
  pet-finder-postgres:
    external: true